# default false
release_mode = false
# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

[app]
    name = "Echo Web"
    #debug or release
    mode = "debug"
[wechat]
    appID = "YOUR_WECHAT_APPID"
    appSecret = "YOUR_WECHAT_APPSECRET"


[muses.app]
	name = "shop-api"
	env = "dev"
	version = "1.0"
[muses.logger.system]
    debug = true
    level = "debug"
    path = "./system.log"
[muses.mysql.mall]
    debug = true
    level = "panic"
    network = "tcp"
    dialect = "mysql"
    addr = "127.0.0.1:3307"
    username = "root"
    password = "root"
    db = "shop"
    charset = "utf8"
    parseTime = "True"
    loc = "Local"
    timeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    maxOpenConns = 30
    maxIdleConns = 10
    connMaxLifetime = "300s"
[muses.redis.auth]
    debug = true
    addr = "127.0.0.1:6379"
    network = "tcp"
    db = 0
    password = ""
    connectTimeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    maxIdle = 5
    maxActive = 20
    idleTimeout = "60s"
    wait = false
[muses.server.stat]
	addr = ":20004"
	writeTimeout = "1s"
	readTimeout = "1s"
[muses.server.gin]
    graceful = true
	mod = "debug"
    addr = ":10004"
    writeTimeout = "10s"
    readTimeout = "10s"
    maxHeaderBytes = 100000000000000
	enabledRecovery = true
	enabledLogger = true
	enabledMetric = true

